[project]
name = 'Tokenized-Decentralized-Outdoor-Shovel-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sharing-coordination]
path = 'contracts/sharing-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage-management]
path = 'contracts/storage-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
